spring.application.name=HiringPlatform
logging.level.org.springframework.data.mongodb=DEBUG
spring.mongodb.database = ram
server.port=5000
spring.mongodb.uri = mongodb+srv://sairamk8128_db_user:sairamk81282005@firstpro.p17j5cc.mongodb.net/?appName=FirstPro